# Generated by Django 5.1.7 on 2025-03-31 09:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostingMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст сообщения')),
                ('file', models.FileField(blank=True, null=True, upload_to='media/', verbose_name='Медиафайл')),
                ('media_type', models.CharField(blank=True, choices=[('image', 'Изображение'), ('video', 'Видео')], max_length=10, null=True, verbose_name='Тип медиафайла')),
                ('send_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время отправки')),
            ],
            options={
                'verbose_name': 'Публикация',
                'verbose_name_plural': 'Публикации',
            },
        ),
    ]
