# Generated by Django 5.1.7 on 2025-04-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0002_startcommandresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='FallbackNotificationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Fallback-уведомление',
                'verbose_name_plural': 'Fallback-уведомление',
            },
        ),
    ]
