# Generated by Django 5.1.7 on 2025-03-31 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Пользователь telegram',
                'verbose_name_plural': 'Пользователи telegram',
            },
        ),
    ]
