# Generated by Django 5.1.7 on 2025-04-01 14:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscription_until',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 9, 28, 14, 13, 0, 986452, tzinfo=datetime.timezone.utc)),
        ),
    ]
