# Generated by Django 5.1.7 on 2025-04-01 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_subscription_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscription_until',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 9, 28, 14, 16, 13, 154363, tzinfo=datetime.timezone.utc)),
        ),
    ]
