# Generated by Django 5.1.7 on 2025-04-01 20:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_is_active_alter_user_subscription_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='not_banned',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscription_until',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 9, 28, 20, 42, 58, 69503, tzinfo=datetime.timezone.utc)),
        ),
    ]
