# Generated by Django 5.1.7 on 2025-04-02 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_subscription_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscription_until',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 9, 29, 10, 16, 37, 52898, tzinfo=datetime.timezone.utc)),
        ),
    ]
