# Generated by Django 5.1.7 on 2025-04-06 14:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_channel_remove_user_is_active_remove_user_not_banned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='channel_id',
            field=models.BigIntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='userchannelsubscription',
            name='subscription_until',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 10, 3, 14, 33, 2, 113748, tzinfo=datetime.timezone.utc)),
        ),
    ]
