# Generated by Django 5.1.7 on 2025-04-08 14:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_channel_channel_id_alter_channel_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchannelsubscription',
            name='subscription_until',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 10, 5, 14, 39, 31, 285551, tzinfo=datetime.timezone.utc)),
        ),
    ]
