# Generated by Django 5.1.7 on 2025-04-11 07:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_userchannelsubscription_subscription_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchannelsubscription',
            name='subscription_until',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 10, 8, 7, 35, 36, 502750, tzinfo=datetime.timezone.utc)),
        ),
    ]
