# Generated by Django 5.1.7 on 2025-05-05 19:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_userchannelsubscription_subscription_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userchannelsubscription',
            name='subscription_until',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 1, 19, 16, 2, 971873, tzinfo=datetime.timezone.utc)),
        ),
    ]
