# Generated by Django 5.1.7 on 2025-05-05 19:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_name_alter_channel_link_alter_channel_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='userchannelsubscription',
            name='subscription_until',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 1, 19, 34, 21, 423735, tzinfo=datetime.timezone.utc)),
        ),
    ]
